In [38]:
import numpy as np

def johnson(data, lmb, inv):
    if inv:
        data_ = data.copy()
    else:
        data_ = data
    new_data = []
    for x in data_:
        
        if x >= 0:
            if lmb == 0:
                new_data.append(np.log(x + 1)) if not inv else new_data.append(np.exp(x)-1)
            else:
                new_data.append(((x + 1)**lmb -1)/lmb) if not inv else new_data.append((lmb*x+1)**(1/lmb) -1)

        if lmb == 2:
            new_data.append(-np.log(1-x)) if not inv else new_data.append(1-np.exp(-x))
        else:
            new_data.append((1-(1-x)**(2-lmb))/(2-lmb)) if not inv else new_data.append(1-(1-(2-lmb)*x)**(1/(2-lmb)))
    return np.array(new_data)
    

In [39]:
orig_data=np.linspace(-10,10,1000)
LMB=[-1,0.5,0,2,3,4]
new_data = {}
for lmb in LMB:
    new_data[lmb] = johnson(orig_data, lmb, True)

data = {}
for lmb in new_data.keys():
    data[lmb] = johnson(new_data[lmb], lmb, False)



C:\Users\anhernan\AppData\Local\Temp\ipykernel_12504\2089222771.py:20: RuntimeWarning: invalid value encountered in scalar power
  new_data.append((1-(1-x)**(2-lmb))/(2-lmb)) if not inv else new_data.append(1-(1-(2-lmb)*x)**(1/(2-lmb)))
C:\Users\anhernan\AppData\Local\Temp\ipykernel_12504\2089222771.py:18: RuntimeWarning: invalid value encountered in log
  new_data.append(-np.log(1-x)) if not inv else new_data.append(1-np.exp(-x))


In [36]:
orig_data

array([-10.        ,  -9.97997998,  -9.95995996,  -9.93993994,
        -9.91991992,  -9.8998999 ,  -9.87987988,  -9.85985986,
        -9.83983984,  -9.81981982,  -9.7997998 ,  -9.77977978,
        -9.75975976,  -9.73973974,  -9.71971972,  -9.6996997 ,
        -9.67967968,  -9.65965966,  -9.63963964,  -9.61961962,
        -9.5995996 ,  -9.57957958,  -9.55955956,  -9.53953954,
        -9.51951952,  -9.4994995 ,  -9.47947948,  -9.45945946,
        -9.43943944,  -9.41941942,  -9.3993994 ,  -9.37937938,
        -9.35935936,  -9.33933934,  -9.31931932,  -9.2992993 ,
        -9.27927928,  -9.25925926,  -9.23923924,  -9.21921922,
        -9.1991992 ,  -9.17917918,  -9.15915916,  -9.13913914,
        -9.11911912,  -9.0990991 ,  -9.07907908,  -9.05905906,
        -9.03903904,  -9.01901902,  -8.998999  ,  -8.97897898,
        -8.95895896,  -8.93893894,  -8.91891892,  -8.8988989 ,
        -8.87887888,  -8.85885886,  -8.83883884,  -8.81881882,
        -8.7987988 ,  -8.77877878,  -8.75875876,  -8.73

In [37]:
data[-1]

array([-10.        ,  -9.97997998,  -9.95995996, ...,          nan,
        -2.80292638,          nan])

In [9]:
data[0.5]

array([-10.        ,  -9.97997998,  -9.95995996, ...,  10.        ,
                nan,          nan])

In [10]:
data[0]

array([-10.        ,  -9.97997998,  -9.95995996, ...,  10.        ,
                nan,  -8.        ])

In [11]:
data[2]

array([-10.        ,  -9.97997998,  -9.95995996, ...,  10.        ,
         1.        ,          nan])

In [12]:
data[3]

array([-10.        ,  -9.97997998,  -9.95995996, ...,  10.        ,
         0.99774944,  10.        ])

In [13]:
data[4]

array([-10.        ,  -9.97997998,  -9.95995996, ...,  10.        ,
         0.98831268,  -8.        ])

`Comparing All the above output we have got inverse of leo-johnson`